// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://yszkkojlqqvevoynucgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlzemtrb2pscXF2ZXZveW51Y2d0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMTQ5NTksImV4cCI6MjA3Mjc5MDk1OX0.2q91hc7SYxbHGPXeXMHzAHbGYoUvqjarvthVDMW4xuI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);